### ISSUE TITLE
`variables.tf` question

### ISSUE THREAD

**Issue by wildsurfer** [webplates/terraform-jmeter#3]
Is there any reason why `ams1` is commented in this file? https://github.com/webplates/terraform-jmeter/blob/master/variables.tf#L34

**Comment by sagikazarmark** [comment]
According to the UI you can't create droplets in the AMS1 region at the moment:

![screen shot 2017-04-11 at 13 32 19](https://cloud.githubusercontent.com/assets/1226384/24907176/6a58d414-1ebb-11e7-82f0-379948338323.png)

**Comment by wildsurfer** [comment]
Ah, good to know :)
